/**
 * BIST (Borsa İstanbul) Tüm İşlem Gören Hisseler Veritabanı
 * A'dan Z'ye 500+ BIST Şirketi, Sektörleri ve Kodları
 */

const BIST_ALL_COMPANIES = [
  // A
  { symbol: 'A1CAP', name: 'A1 Capital Yatırım Menkul Değerler', sector: 'Aracı Kurum & Finans', price: 29.50 },
  { symbol: 'ACSEL', name: 'Acıselsan Acıpayam Selüloz', sector: 'Kimya & Kağıt', price: 138.00 },
  { symbol: 'ADEL', name: 'Adel Kalemcilik', sector: 'Kırtasiye & İmalat', price: 540.00 },
  { symbol: 'ADESE', name: 'Adese Gayrimenkul Yatırım', sector: 'Gayrimenkul Yatırım', price: 2.15 },
  { symbol: 'ADGYO', name: 'Adra Gayrimenkul Yatırım Ortaklığı', sector: 'GYO', price: 34.80 },
  { symbol: 'AEFES', name: 'Anadolu Efes Biracılık ve Malt Sanayii', sector: 'İçecek & Meşrubat', price: 215.00 },
  { symbol: 'AFYON', name: 'Afyon Çimento Sanayi', sector: 'Çimento & Yapı', price: 13.80 },
  { symbol: 'AGESA', name: 'Agesa Hayat ve Emeklilik', sector: 'Sigortacılık', price: 114.00 },
  { symbol: 'AGHOL', name: 'Anadolu Grubu Holding', sector: 'Holding & Yatırım', price: 365.00 },
  { symbol: 'AGROT', name: 'Agrotech Yüksek Teknoloji ve Tarım', sector: 'Yazılım & Tarım', price: 14.50 },
  { symbol: 'AHGAZ', name: 'Ahlatcı Doğal Gaz Dağıtım', sector: 'Enerji & Gaz Dağıtım', price: 13.40 },
  { symbol: 'AKBNK', name: 'Akbank T.A.Ş.', sector: 'Bankacılık', price: 58.70 },
  { symbol: 'AKCNS', name: 'Akçansa Çimento Sanayi', sector: 'Çimento & Yapı', price: 142.00 },
  { symbol: 'AKENR', name: 'Akenerji Elektrik Üretim', sector: 'Elektrik & Enerji', price: 18.20 },
  { symbol: 'AKFGY', name: 'Akfen Gayrimenkul Yatırım Ortaklığı', sector: 'GYO', price: 2.30 },
  { symbol: 'AKFYE', name: 'Akfen Yenilenebilir Enerji', sector: 'Yenilenebilir Enerji', price: 22.80 },
  { symbol: 'AKGRT', name: 'Aksigorta A.Ş.', sector: 'Sigortacılık', price: 6.80 },
  { symbol: 'AKMGY', name: 'Akmerkez Gayrimenkul Yatırım Ortaklığı', sector: 'GYO', price: 285.00 },
  { symbol: 'AKSA', name: 'Aksa Akrilik Kimya Sanayii', sector: 'Kimya & Elyaf', price: 11.40 },
  { symbol: 'AKSEN', name: 'Aksa Enerji Üretim', sector: 'Enerji & Elektrik', price: 38.50 },
  { symbol: 'AKSUE', name: 'Aksu Enerji ve Ticaret', sector: 'Enerji', price: 38.00 },
  { symbol: 'AKYHO', name: 'Akdeniz Yatırım Holding', sector: 'Holding', price: 5.60 },
  { symbol: 'ALARK', name: 'Alarko Holding A.Ş.', sector: 'Holding & Enerji', price: 95.80 },
  { symbol: 'ALBRK', name: 'Albaraka Türk Katılım Bankası', sector: 'Katılım Bankacılığı', price: 5.40 },
  { symbol: 'ALCAR', name: 'Alarko Carrier Sanayi ve Ticaret', sector: 'İklimlendirme', price: 1250.00 },
  { symbol: 'ALCTL', name: 'Alcatel Lucent Teletaş Telekomünikasyon', sector: 'Telekom & Teknoloji', price: 104.00 },
  { symbol: 'ALFAS', name: 'Alfa Solar Enerji Sanayi', sector: 'Güneş Enerjisi', price: 67.50 },
  { symbol: 'ALGYO', name: 'Alarko Gayrimenkul Yatırım Ortaklığı', sector: 'GYO', price: 42.60 },
  { symbol: 'ALKA', name: 'Alkim Kağıt Sanayi ve Ticaret', sector: 'Kağıt & Ambalaj', price: 26.80 },
  { symbol: 'ALKIM', name: 'Alkim Alkali Kimya', sector: 'Kimya Madencilik', price: 31.40 },
  { symbol: 'ALKLC', name: 'Altınkılıç Gıda ve Süt Sanayi', sector: 'Gıda & Süt Ürünleri', price: 28.50 },
  { symbol: 'ALMAD', name: 'Altınyağ Madencilik ve Kimya', sector: 'Madencilik & Yağ', price: 6.90 },
  { symbol: 'ALTIN', name: 'Darphane Altın Sertifikası (ALTIN.S1)', sector: 'Kıymetli Madenler', price: 34.50 },
  { symbol: 'ALTNY', name: 'Altınay Savunma Teknolojileri', sector: 'Savunma Sanayii & Robotik', price: 95.50 },
  { symbol: 'ALVES', name: 'Alves Kablo Sanayi ve Ticaret', sector: 'Kablo & Metal Sanayi', price: 36.20 },
  { symbol: 'ANELE', name: 'Anel Elektrik Proje Taahhüt', sector: 'Elektrik Taahhüt', price: 18.50 },
  { symbol: 'ANGEN', name: 'Anatolia Tanı ve Biyoteknoloji', sector: 'Biyoteknoloji & Sağlık', price: 13.80 },
  { symbol: 'ANHYT', name: 'Anadolu Hayat Emeklilik', sector: 'Bireysel Emeklilik & Hayat', price: 108.00 },
  { symbol: 'ANSGR', name: 'Anadolu Anonim Türk Sigorta Şirketi', sector: 'Sigortacılık', price: 92.50 },
  { symbol: 'ARCLK', name: 'Arçelik A.Ş.', sector: 'Dayanıklı Tüketim & Beyaz Eşya', price: 162.00 },
  { symbol: 'ARDYZ', name: 'Ard Grup Bilişim Teknolojileri', sector: 'Yazılım & Bilişim', price: 38.60 },
  { symbol: 'ARENA', name: 'Arena Bilgisayar Sanayi', sector: 'Bilişim & Dağıtım', price: 39.50 },
  { symbol: 'ARSAN', name: 'Arsan Tekstil Ticaret ve Sanayi', sector: 'Tekstil', price: 14.80 },
  { symbol: 'ARTMS', name: 'Artemis Halı A.Ş.', sector: 'Halı & Ev Tekstili', price: 32.40 },
  { symbol: 'ARZUM', name: 'Arzum Elektrikli Ev Aletleri', sector: 'Küçük Ev Aletleri', price: 44.20 },
  { symbol: 'ASELS', name: 'Aselsan Elektronik Sanayi', sector: 'Savunma Sanayii', price: 63.80 },
  { symbol: 'ASGYO', name: 'Asce Gayrimenkul Yatırım Ortaklığı', sector: 'GYO', price: 12.80 },
  { symbol: 'ASTOR', name: 'Astor Enerji A.Ş.', sector: 'Transformatör & Enerji', price: 96.50 },
  { symbol: 'ASUZU', name: 'Anadolu Isuzu Otomotiv Sanayi', sector: 'Ticari Araç & Otomotiv', price: 212.00 },
  { symbol: 'ATAGY', name: 'Ata Gayrimenkul Yatırım Ortaklığı', sector: 'GYO', price: 8.90 },
  { symbol: 'ATEKS', name: 'Akın Tekstil A.Ş.', sector: 'Tekstil', price: 122.00 },
  { symbol: 'ATAKP', name: 'Atakey Patates Gıda Sanayi', sector: 'Dondurulmuş Gıda', price: 41.50 },
  { symbol: 'ATLAS', name: 'Atlas Menkul Kıymetler Yatırım', sector: 'Menkul Kıymetler', price: 5.80 },
  { symbol: 'ATSYH', name: 'Atlantis Yatırım Holding', sector: 'Holding', price: 42.00 },
  { symbol: 'AVGYO', name: 'Avrasya Gayrimenkul Yatırım Ortaklığı', sector: 'GYO', price: 8.50 },
  { symbol: 'AVHOL', name: 'Avrupa Yatırım Holding', sector: 'Holding & Sağlık', price: 34.20 },
  { symbol: 'AVOD', name: 'A.V.O.D. Kurutulmuş Gıda ve Sebze', sector: 'Gıda İhracatı', price: 3.40 },
  { symbol: 'AVPGY', name: 'Avrupakent Gayrimenkul Yatırım Ortaklığı', sector: 'GYO', price: 48.00 },
  { symbol: 'AYCES', name: 'Altın Yunus Çeşme Turistik Tesisler', sector: 'Turizm & Otelcilik', price: 580.00 },
  { symbol: 'AYDEM', name: 'Aydem Yenilenebilir Enerji', sector: 'Yenilenebilir Enerji', price: 24.50 },
  { symbol: 'AYEN', name: 'Ayen Enerji A.Ş.', sector: 'Enerji Üretimi', price: 33.00 },
  { symbol: 'AYES', name: 'Ayes Çelik Hasır ve Çit Sanayi', sector: 'Çelik Hasır & İnşaat', price: 39.00 },
  { symbol: 'AYGAZ', name: 'Aygaz A.Ş.', sector: 'LPG & Enerji Dağıtım', price: 168.00 },
  { symbol: 'AZTEK', name: 'Aztek Teknoloji Ürünleri', sector: 'Tüketici Elektroniği Dağıtımı', price: 82.50 },

  // B
  { symbol: 'BAGFS', name: 'Bağfaş Bandırma Gübre Fabrikaları', sector: 'Kimyevi Gübre', price: 28.40 },
  { symbol: 'BAKAB', name: 'Bak Ambalaj Sanayi', sector: 'Esnek Ambalaj', price: 52.00 },
  { symbol: 'BALAT', name: 'Balatacılar Balatacılık Sanayi', sector: 'Otomotiv Fren Balatası', price: 18.50 },
  { symbol: 'BANVT', name: 'Banvit Bandırma Vitaminli Yem Sanayii', sector: 'Beyaz Et & Gıda', price: 290.00 },
  { symbol: 'BARMA', name: 'Barem Ambalaj Sanayi', sector: 'Oluklu Mukavva & Ambalaj', price: 19.80 },
  { symbol: 'BASCM', name: 'Baştaş Başkent Çimento Sanayi', sector: 'Çimento', price: 15.60 },
  { symbol: 'BASGZ', name: 'Başkent Doğalgaz Dağıtım', sector: 'Doğalgaz Dağıtım', price: 21.40 },
  { symbol: 'BAYRK', name: 'Bayrak EBT Taban Sanayi', sector: 'Ayakkabı Tabanı & Plastik', price: 16.20 },
  { symbol: 'BEGYO', name: 'Batı Ege Gayrimenkul Yatırım Ortaklığı', sector: 'GYO', price: 3.80 },
  { symbol: 'BERA', name: 'Bera Holding A.Ş.', sector: 'Holding & İmalat', price: 16.90 },
  { symbol: 'BEYAZ', name: 'Beyaz Filo Oto Kiralama', sector: 'Filo Kiralama & İkinci El', price: 17.50 },
  { symbol: 'BFREN', name: 'Bosch Fren Sistemleri Sanayi', sector: 'Otomotiv Fren Sistemleri', price: 920.00 },
  { symbol: 'BIENY', name: 'Bien Yapı Ürünleri Sanayi', sector: 'Seramik & Vitrifiye', price: 38.50 },
  { symbol: 'BIGCH', name: 'Big Chefs (Büyük Şefler Döner)', sector: 'Restoran Zinciri & Gıda', price: 29.80 },
  { symbol: 'BIMAS', name: 'BİM Birleşik Mağazalar A.Ş.', sector: 'Perakende Market Zinciri', price: 546.00 },
  { symbol: 'BINHO', name: '1000 Yatırımlar Holding (BinBin)', sector: 'Mikromobilite & Holding', price: 320.00 },
  { symbol: 'BIOEN', name: 'Biotrend Çevre ve Enerji Yatırımları', sector: 'Biyokütle Enerjisi', price: 18.50 },
  { symbol: 'BIZIM', name: 'Bizim Toptan Satış Mağazaları', sector: 'Toptan Market', price: 36.80 },
  { symbol: 'BJKAS', name: 'Beşiktaş Futbol Yatırımları Sanayi', sector: 'Spor Kulübü', price: 6.40 },
  { symbol: 'BLCYT', name: 'Bilici Yatırım Sanayi ve Ticaret', sector: 'Tekstil & Turizm', price: 18.20 },
  { symbol: 'BNTAS', name: 'Bantaş Bandırma Ambalaj Sanayi', sector: 'Metal Ambalaj & Teneke Kutu', price: 9.40 },
  { symbol: 'BOBET', name: 'Boğaziçi Beton Sanayi ve Ticaret', sector: 'Hazır Beton & Madencilik', price: 29.50 },
  { symbol: 'BORLS', name: 'Borlease Otomotiv A.Ş.', sector: 'Uzun Dönem Araç Kiralama', price: 28.50 },
  { symbol: 'BORSK', name: 'Bor Şeker A.Ş.', sector: 'Şeker Üretimi & Tarım', price: 32.00 },
  { symbol: 'BOSSA', name: 'Bossa Ticaret ve Sanayi İşletmeleri', sector: 'Denim & Tekstil', price: 11.20 },
  { symbol: 'BRISA', name: 'Brisa Bridgestone Sabancı Lastik', sector: 'Otomotiv Lastiği', price: 112.00 },
  { symbol: 'BRKO', name: 'Birko Birleşik Koyunlular Mensucat', sector: 'İplik & Halı', price: 7.80 },
  { symbol: 'BRKSN', name: 'Berkosan Yalıtım ve Tecrit Maddeleri', sector: 'Polietilen Yalıtım', price: 28.40 },
  { symbol: 'BRKVY', name: 'Birikim Varlık Yönetim', sector: 'Finansal Varlık Yönetimi', price: 118.00 },
  { symbol: 'BRLSM', name: 'Birleşim Mühendislik Isıtma Soğutma', sector: 'Mekanik & Elektrik Taahhüt', price: 21.60 },
  { symbol: 'BRMEN', name: 'Birlik Mensucat Ticaret', sector: 'Ev Tekstili', price: 4.80 },
  { symbol: 'BRSAN', name: 'Borusan Boru Sanayi ve Ticaret', sector: 'Çelik Boru & Sanayi', price: 540.00 },
  { symbol: 'BRYAT', name: 'Borusan Yatırım ve Pazarlama', sector: 'Holding & Sanayi', price: 2350.00 },
  { symbol: 'BSOKE', name: 'Batısöke Söke Çimento Sanayii', sector: 'Çimento & Klinker', price: 16.50 },
  { symbol: 'BTCIM', name: 'Batıçim Batı Anadolu Çimento Sanayii', sector: 'Çimento & Enerji', price: 168.00 },
  { symbol: 'BUCIM', name: 'Bursa Çimento Fabrikası', sector: 'Çimento', price: 8.90 },
  { symbol: 'BURCE', name: 'Bursa Çelik Döküm Sanayi', sector: 'Çelik Döküm & Vana', price: 185.00 },
  { symbol: 'BURVA', name: 'Burçelik Vana Sanayi ve Ticaret', sector: 'Endüstriyel Vana', price: 128.00 },
  { symbol: 'BVSAN', name: 'Bülbüloğlu Vinç Sanayi', sector: 'Endüstriyel Vinç İmalatı', price: 88.00 },
  { symbol: 'BYDNR', name: 'Baydöner Restoranları A.Ş.', sector: 'Döner Restoran Zinciri', price: 26.50 },

  // C - Ç
  { symbol: 'CANTE', name: 'Çan2 Termik A.Ş.', sector: 'Termik Enerji & Kömür', price: 16.20 },
  { symbol: 'CATES', name: 'Çates Elektrik Üretim', sector: 'Termik Santral & Enerji', price: 48.00 },
  { symbol: 'CCOLA', name: 'Coca-Cola İçecek A.Ş.', sector: 'Alkolsüz İçecekler', price: 68.50 },
  { symbol: 'CELHA', name: 'Çelik Halat ve Tel Sanayii', sector: 'Çelik Halat & Tel', price: 48.00 },
  { symbol: 'CEMAS', name: 'Çemaş Döküm Sanayi', sector: 'Döküm & Metalurji', price: 3.80 },
  { symbol: 'CEMTS', name: 'Çemtaş Çelik Makina Sanayi', sector: 'Vasıflı Çelik & Denge Çubuğu', price: 11.20 },
  { symbol: 'CEOEM', name: 'Ceo Event Medya A.Ş.', sector: 'Etkinlik & Kongre Organizasyonu', price: 24.50 },
  { symbol: 'CIMSA', name: 'Çimsa Çimento Sanayi ve Ticaret', sector: 'Beyaz Çimento & Yapı', price: 34.20 },
  { symbol: 'CLEBI', name: 'Çelebi Hava Servisi', sector: 'Yer Hizmetleri & Kargo', price: 1680.00 },
  { symbol: 'CONSE', name: 'Consus Enerji İşletmeciliği', sector: 'Biyokütle & Güneş Enerjisi', price: 6.90 },
  { symbol: 'COSMO', name: 'Cosmos Yatırım Holding', sector: 'Holding & Mühendislik', price: 165.00 },
  { symbol: 'CRDFA', name: 'Creditwest Faktoring', sector: 'Faktoring & Finans', price: 9.80 },
  { symbol: 'CRFSA', name: 'CarrefourSA Carrefour Sabancı Ticaret', sector: 'Süpermarket Zinciri', price: 135.00 },
  { symbol: 'CUSAN', name: 'Çuhadaroğlu Metal Sanayi', sector: 'Alüminyum Mimari Sistemler', price: 19.80 },
  { symbol: 'CVKMD', name: 'CVK Maden İşletmeleri', sector: 'Krom & Altın Madenciliği', price: 420.00 },
  { symbol: 'CWENE', name: 'CW Enerji Mühendislik', sector: 'Güneş Paneli Üretimi', price: 192.00 },

  // D
  { symbol: 'DAGI', name: 'Dagi Giyim Sanayi ve Ticaret', sector: 'İç Giyim & Perakende', price: 18.50 },
  { symbol: 'DAGHL', name: 'Dagi Yatırım Holding', sector: 'Holding', price: 26.00 },
  { symbol: 'DAPGM', name: 'Dap Gayrimenkul Geliştirme', sector: 'Konut Projeleri & GYO', price: 26.80 },
  { symbol: 'DARDL', name: 'Dardanel Önentaş Gıda Sanayi', sector: 'Ton Balığı & Konserve', price: 5.60 },
  { symbol: 'DENGE', name: 'Denge Yatırım Holding', sector: 'Holding', price: 3.20 },
  { symbol: 'DERHL', name: 'Derlüks Yatırım Holding', sector: 'Deri Konfeksiyon & Holding', price: 16.50 },
  { symbol: 'DERIM', name: 'Derimod Konfeksiyon Ayakkabı Deri', sector: 'Deri Ayakkabı & Mont', price: 21.00 },
  { symbol: 'DESA', name: 'Desa Deri Sanayi ve Ticaret', sector: 'Deri Çanta & Ayakkabı', price: 21.40 },
  { symbol: 'DESPC', name: 'Despec Bilgisayar Pazarlama', sector: 'Bilişim Sarf Malzemeleri', price: 38.00 },
  { symbol: 'DEVA', name: 'Deva Holding A.Ş.', sector: 'İlaç Sanayii & Sağlık', price: 96.50 },
  { symbol: 'DGGYO', name: 'Doğuş Gayrimenkul Yatırım Ortaklığı', sector: 'GYO (Doğuş Center)', price: 48.00 },
  { symbol: 'DGPAP', name: 'Doğan Trend Otomotiv / Doğan Gazetecilik', sector: 'Medya & Otomotiv', price: 6.80 },
  { symbol: 'DIRIT', name: 'Diriteks Diriliş Tekstil Sanayi', sector: 'Battaniye & Akrilik İplik', price: 9.50 },
  { symbol: 'DITAS', name: 'Ditaş Doğan Yedek Parça İmalat', sector: 'Otomotiv Direksiyon & Süspansiyon', price: 19.80 },
  { symbol: 'DMSAS', name: 'Demisaş Döküm Emaye Mamulleri', sector: 'Pik & Sfero Döküm', price: 9.80 },
  { symbol: 'DNISI', name: 'Dinamik Isı Makina Yalıtım', sector: 'Polietilen Yalıtım', price: 11.40 },
  { symbol: 'DOAS', name: 'Doğuş Otomotiv Servis ve Ticaret', sector: 'Otomotiv Distribütörlüğü (VW, Audi, Porsche)', price: 275.00 },
  { symbol: 'DOCO', name: 'DO & CO Aktiengesellschaft', sector: 'Uçak İçi İkram & Ağırlama', price: 5600.00 },
  { symbol: 'DOFER', name: 'Dofer Yapı Malzemeleri', sector: 'Çelik Hasır & Demir Ticareti', price: 39.50 },
  { symbol: 'DOGUB', name: 'Doğusan Boru Sanayii', sector: 'Beton Boru & Kiremit', price: 18.00 },
  { symbol: 'DOHOL', name: 'Doğan Şirketler Grubu Holding', sector: 'Holding & Enerji / Sanayi', price: 14.50 },
  { symbol: 'DOKTA', name: 'Döktaş Dökümcülük Ticaret', sector: 'Otomotiv Demir & Alüminyum Döküm', price: 42.00 },
  { symbol: 'DURDO', name: 'Duran Doğan Basım ve Ambalaj', sector: 'Karton Ambalaj & Baskı', price: 16.80 },
  { symbol: 'DURKN', name: 'Durukan Şekerleme Sanayi', sector: 'Lolipop & Şekerleme İhracatı', price: 17.50 },
  { symbol: 'DYOBY', name: 'Dyo Boya Fabrikaları Sanayi', sector: 'İnşaat & Sanayi Boyaları', price: 28.50 },
  { symbol: 'DZGYO', name: 'Deniz Gayrimenkul Yatırım Ortaklığı', sector: 'GYO', price: 6.80 },

  // E
  { symbol: 'EBEBK', name: 'Ebebek Mağazacılık A.Ş.', sector: 'Anne & Bebek Ürünleri Mağazacılığı', price: 48.00 },
  { symbol: 'ECILC', name: 'Eczacıbaşı İlaç Sınai ve Finansal', sector: 'İlaç & Sağlık', price: 54.00 },
  { symbol: 'ECZYT', name: 'Eczacıbaşı Yatırım Holding', sector: 'Yatırım Holding', price: 245.00 },
  { symbol: 'EDATA', name: 'E-Data Teknoloji Bilişim', sector: 'Siber Güvenlik Dağıtımı', price: 21.50 },
  { symbol: 'EDIP', name: 'Edip Gayrimenkul Yatırım', sector: 'Gayrimenkul', price: 18.50 },
  { symbol: 'EGEEN', name: 'Ege Endüstri ve Ticaret A.Ş.', sector: 'Ağır Vasıta Dingil & Süspansiyon', price: 11200.00 },
  { symbol: 'EGGUB', name: 'Ege Gübre Sanayii', sector: 'Gübre İmalatı & Liman İşletmeciliği', price: 58.00 },
  { symbol: 'EGPRO', name: 'Ege Profil Ticaret ve Sanayi (Egepen)', sector: 'PVC Profil & Pencere', price: 215.00 },
  { symbol: 'EGSER', name: 'Ege Seramik Sanayi ve Ticaret', sector: 'Seramik Karo', price: 4.80 },
  { symbol: 'EKGYO', name: 'Emlak Konut Gayrimenkul Yatırım Ortaklığı', sector: 'Gayrimenkul Yatırım & Konut', price: 11.80 },
  { symbol: 'EKSUN', name: 'Eksun Gıda Tarım Sanayi (Sinangil Un)', sector: 'Un & Gıda Sanayii', price: 58.50 },
  { symbol: 'ELITE', name: 'Elite Naturel Organik Gıda', sector: 'Organik Meyve Suyu', price: 42.00 },
  { symbol: 'EMKEL', name: 'Emek Elektrik Endüstrisi', sector: 'Ölçü Transformatörleri', price: 34.50 },
  { symbol: 'ENERY', name: 'Enerya Enerji A.Ş.', sector: 'Şehir Doğalgaz Dağıtımı', price: 210.00 },
  { symbol: 'ENJSA', name: 'Enerjisa Enerji A.Ş.', sector: 'Elektrik Dağıtım & Perakende Satış', price: 62.50 },
  { symbol: 'ENKAI', name: 'Enka İnşaat ve Sanayi A.Ş.', sector: 'Uluslararası İnşaat & Enerji', price: 42.50 },
  { symbol: 'ENSRI', name: 'Ensari Deri Gıda Sanayi', sector: 'Kürk Süet & Deri İşleme', price: 28.00 },
  { symbol: 'EPLAS', name: 'Egeplast Ege Plastik Ticaret', sector: 'Plastik Boru & Ek Parçalar', price: 8.50 },
  { symbol: 'ERBOS', name: 'Erbosan Erciyas Boru Sanayii', sector: 'Dikişli Çelik Boru', price: 185.00 },
  { symbol: 'EREGL', name: 'Ereğli Demir ve Çelik Fabrikaları', sector: 'Yassı Çelik & Ağır Sanayi', price: 51.90 },
  { symbol: 'ERSU', name: 'Ersu Meyve Suları Sanayi', sector: 'Meyve Suyu Konsantresi', price: 34.00 },
  { symbol: 'ESCAR', name: 'Escar Filo Kiralama Hizmetleri', sector: 'Operasyonel Filo Kiralama', price: 310.00 },
  { symbol: 'ESCOM', name: 'Escort Teknoloji Yatırım', sector: 'Girişim Sermayesi & Teknoloji', price: 48.00 },
  { symbol: 'ETILR', name: 'Etiler Gıda ve Ticari Yatırımlar', sector: 'Gıda & Fast Food Zinciri', price: 28.00 },
  { symbol: 'EUPWR', name: 'Europower Enerji ve Otomasyon', sector: 'Yüksek Gerilim & Otomasyon', price: 91.20 },
  { symbol: 'EUREN', name: 'Europen Endüstri İnşaat Sanayi', sector: 'Cam & PVC Profil İmalatı', price: 13.80 },
  { symbol: 'EYGYO', name: 'EYG Gayrimenkul Yatırım Ortaklığı', sector: 'GYO', price: 8.50 },

  // F
  { symbol: 'FADE', name: 'Fade Gıda Yatırım Sanayi', sector: 'Kurutulmuş Domates & Fide', price: 14.20 },
  { symbol: 'FENER', name: 'Fenerbahçe Futbol A.Ş.', sector: 'Spor Kulübü & Mağazacılık', price: 98.00 },
  { symbol: 'FMIZP', name: 'Federal Mogul İzmit Piston', sector: 'Motor Pistonu & Segman', price: 285.00 },
  { symbol: 'FONET', name: 'Fonet Bilgi Teknolojileri', sector: 'Sağlık Bilişim Sistemleri (HBYS)', price: 18.50 },
  { symbol: 'FORMT', name: 'Formet Metal ve Cam Sanayi', sector: 'Çelik Kapı & Isıtıcı', price: 3.40 },
  { symbol: 'FORTE', name: 'Forte Bilgi İletişim Teknolojileri', sector: 'Sistem Entegrasyonu & Savunma', price: 54.00 },
  { symbol: 'FRIGO', name: 'Frigo-Pak Gıda Maddeleri Sanayi', sector: 'Narenciye Konservesi', price: 7.80 },
  { symbol: 'FROTO', name: 'Ford Otomotiv Sanayi A.Ş.', sector: 'Ticari Araç & Otomobil İmalatı', price: 1085.00 },
  { symbol: 'FZLGY', name: 'Fuzul Gayrimenkul Yatırım Ortaklığı', sector: 'GYO', price: 16.50 },

  // G
  { symbol: 'GARAN', name: 'Türkiye Garanti Bankası A.Ş.', sector: 'Bankacılık', price: 118.50 },
  { symbol: 'GARFA', name: 'Garanti Faktoring', sector: 'Faktoring', price: 82.00 },
  { symbol: 'GEDIK', name: 'Gedik Yatırım Menkul Değerler', sector: 'Aracı Kurum', price: 12.80 },
  { symbol: 'GEDZA', name: 'Gediz Ambalaj Sanayi', sector: 'Plastik Oluklu Levha', price: 38.00 },
  { symbol: 'GENIL', name: 'Gen İlaç ve Sağlık Ürünleri', sector: 'Yetim İlaç & İlaç Üretimi', price: 68.50 },
  { symbol: 'GENTS', name: 'Gentaş Dekoratif Yüzeyler Sanayi', sector: 'Laminat & Kompakt Panel', price: 8.90 },
  { symbol: 'GEREL', name: 'Gersan Elektrik Ticaret', sector: 'Bara & Elektrikli Araç Şarjı', price: 28.50 },
  { symbol: 'GESAN', name: 'Girişim Elektrik Taahhüt Ticaret', sector: 'Yenilenebilir Enerji Santralleri', price: 49.30 },
  { symbol: 'GIPTA', name: 'Gıpta Ofis Kırtasiye ve Ambalaj', sector: 'Defter, Ajanda & Kırtasiye', price: 28.50 },
  { symbol: 'GLBMD', name: 'Global Menkul Değerler', sector: 'Aracı Kurum', price: 48.00 },
  { symbol: 'GLCVY', name: 'Gelecek Varlık Yönetimi', sector: 'Tahsilat & Varlık Yönetimi', price: 42.00 },
  { symbol: 'GLRYH', name: 'Güler Yatırım Holding', sector: 'Holding', price: 14.80 },
  { symbol: 'GLYHO', name: 'Global Yatırım Holding', sector: 'Kruvaziyer Liman İşletmeciliği', price: 13.80 },
  { symbol: 'GOKNR', name: 'Göknur Gıda Maddeleri', sector: 'Meyve Suyu Konsantresi & Meyvecilik', price: 23.50 },
  { symbol: 'GOLTS', name: 'Göltaş Göller Bölgesi Çimento', sector: 'Çimento & Hazır Beton', price: 420.00 },
  { symbol: 'GOODY', name: 'Goodyear Lastikleri T.A.Ş.', sector: 'Otomotiv Lastiği', price: 22.80 },
  { symbol: 'GOZDE', name: 'Gözde Girişim Sermayesi Yatırım', sector: 'Özel Sermaye Girişimi (Yıldız Holding)', price: 26.80 },
  { symbol: 'GRNYO', name: 'Garanti Yatırım Ortaklığı', sector: 'Menkul Kıymet Yatırım Ortaklığı', price: 9.80 },
  { symbol: 'GSDDE', name: 'GSD Denizcilik Gayrimenkul', sector: 'Deniz Taşımacılığı (Kuru Yük)', price: 11.20 },
  { symbol: 'GSDHO', name: 'GSD Holding A.Ş.', sector: 'Holding & Bankacılık / Denizcilik', price: 4.80 },
  { symbol: 'GSRAY', name: 'Galatasaray Sportif Sınai ve Ticari', sector: 'Spor Kulübü & Lisanslı Ürünler', price: 7.80 },
  { symbol: 'GUBRF', name: 'Gübre Fabrikaları T.A.Ş. (Gübretaş)', sector: 'Kimyevi Gübre & Tarımsal Girdiler', price: 185.00 },
  { symbol: 'GWIND', name: 'Galata Wind Enerji A.Ş.', sector: 'Rüzgar ve Güneş Enerjisi Üretimi', price: 27.50 },
  { symbol: 'GZNMI', name: 'Gezinomi Seyahat Turizm', sector: 'Online Turizm & Otel Rezervasyonu', price: 44.00 },

  // H - I - İ
  { symbol: 'HALKB', name: 'Türkiye Halk Bankası A.Ş.', sector: 'Kamu Bankacılığı', price: 17.80 },
  { symbol: 'HATEK', name: 'Hateks Hatay Tekstil İşletmeleri', sector: 'Pamuk İpliği & Havlu', price: 14.50 },
  { symbol: 'HATSN', name: 'Hat-San Gemi İnşaa Bakım Onarım', sector: 'Tersane & Gemi Tamiri', price: 48.00 },
  { symbol: 'HDFGS', name: 'Hedef Girişim Sermayesi Yatırım', sector: 'Girişim Sermayesi', price: 2.80 },
  { symbol: 'HEDEF', name: 'Hedef Holding A.Ş.', sector: 'Holding & Finans', price: 21.00 },
  { symbol: 'HEKTS', name: 'Hektaş Ticaret T.A.Ş.', sector: 'Bitki Koruma & Hayvan Sağlığı', price: 3.95 },
  { symbol: 'HKTM', name: 'Hidropar Hareket Kontrol Teknolojileri', sector: 'Mühendislik & Robotik Otomasyon', price: 24.80 },
  { symbol: 'HLGYO', name: 'Halk Gayrimenkul Yatırım Ortaklığı', sector: 'GYO (İstanbul Finans Merkezi)', price: 4.20 },
  { symbol: 'HRKET', name: 'Hareket Proje Taşımacılığı ve Yük Mühendisliği', sector: 'Ağır Yük Taşımacılığı & Vinç', price: 72.00 },
  { symbol: 'HTTBT', name: 'Hitit Bilgisayar Hizmetleri', sector: 'Havacılık Yazılımı & PSS Çözümleri', price: 78.50 },
  { symbol: 'HUBVC', name: 'Hub Girişim Sermayesi Yatırım', sector: 'Erken Aşama Girişim Sermayesi', price: 7.80 },
  { symbol: 'HUNER', name: 'Hun Yenilenebilir Enerji', sector: 'Güneş & Biyokütle Enerjisi', price: 4.80 },
  { symbol: 'HURGZ', name: 'Hürriyet Gazetecilik ve Matbaacılık', sector: 'Yazılı Medya & Matbaacılık', price: 5.60 },
  { symbol: 'ICBCT', name: 'ICBC Turkey Bank A.Ş.', sector: 'Bankacılık', price: 12.80 },
  { symbol: 'ICUGS', name: 'IC Enterra Yenilenebilir Enerji', sector: 'Hidroelektrik & Güneş Enerjisi', price: 11.20 },
  { symbol: 'IDGYO', name: 'İdealist Gayrimenkul Yatırım Ortaklığı', sector: 'GYO', price: 5.80 },
  { symbol: 'IEYHO', name: 'Işıklar Enerji ve Yapı Holding', sector: 'Holding', price: 4.20 },
  { symbol: 'IHLAS', name: 'İhlas Holding A.Ş.', sector: 'Holding', price: 1.25 },
  { symbol: 'IHLGM', name: 'İhlas Gayrimenkul Proje Geliştirme', sector: 'İnşaat & Gayrimenkul', price: 1.45 },
  { symbol: 'IMASM', name: 'İmaş Makina Sanayi', sector: 'Değirmen Makineleri İmalatı', price: 14.80 },
  { symbol: 'INDES', name: 'İndeks Bilgisayar Sistemleri', sector: 'Bilişim Teknolojileri Distribütörlüğü', price: 8.90 },
  { symbol: 'INFO', name: 'İnfo Yatırım Menkul Değerler', sector: 'Aracı Kurum & Portföy', price: 11.80 },
  { symbol: 'INVES', name: 'Investco Holding A.Ş.', sector: 'Holding & Girişim', price: 295.00 },
  { symbol: 'IPEKE', name: 'İpek Doğal Enerji Kaynakları', sector: 'Petrol & Doğal Gaz Arama', price: 39.50 },
  { symbol: 'ISCTR', name: 'Türkiye İş Bankası (C)', sector: 'Bankacılık', price: 14.20 },
  { symbol: 'ISDMR', name: 'İskenderun Demir ve Çelik A.Ş.', sector: 'Entegre Yassı & Uzun Çelik', price: 38.50 },
  { symbol: 'ISFIN', name: 'İş Finansal Kiralama (İş Leasing)', sector: 'Finansal Kiralama', price: 12.40 },
  { symbol: 'ISGYO', name: 'İş Gayrimenkul Yatırım Ortaklığı', sector: 'GYO (İş Kuleleri)', price: 16.50 },
  { symbol: 'ISKPL', name: 'Işık Plastik Sanayi ve Dış Ticaret', sector: 'Akrilik & Polikarbonat Levha', price: 11.80 },
  { symbol: 'ISMEN', name: 'İş Yatırım Menkul Değerler', sector: 'Yatırım Bankacılığı & Aracı Kurum', price: 34.50 },
  { symbol: 'IZMDC', name: 'İzmir Demir Çelik Sanayi', sector: 'İnşaat Demiri & Kütük Çelik', price: 6.80 },

  // K
  { symbol: 'KAREL', name: 'Karel Elektronik Sanayi', sector: 'Telekomünikasyon Santralleri & Savunma', price: 12.80 },
  { symbol: 'KARSN', name: 'Karsan Otomotiv Sanayii', sector: 'Elektrikli Minibüs & Otobüs', price: 13.50 },
  { symbol: 'KARTN', name: 'Kartonsan Karton Sanayi ve Ticaret', sector: 'Kuşeli Karton İmalatı', price: 118.00 },
  { symbol: 'KAYSE', name: 'Kayseri Şeker Fabrikası', sector: 'Şeker Üretimi & Tarımsal Sanayi', price: 26.50 },
  { symbol: 'KBORU', name: 'Kuzey Boru A.Ş.', sector: 'Altyapı Plastik Boruları (PE100)', price: 82.00 },
  { symbol: 'KCAER', name: 'Kocaer Çelik Sanayi ve Ticaret', sector: 'Çelik Profil & Enerji Çeliği', price: 58.00 },
  { symbol: 'KCHOL', name: 'Koç Holding A.Ş.', sector: 'Türkiye\'nin En Büyük Sanayi ve Hizmet Grubu', price: 212.00 },
  { symbol: 'KFEIN', name: 'Kafein Yazılım Hizmetleri', sector: 'Yazılım & Telekom Çözümleri', price: 118.00 },
  { symbol: 'KLKIM', name: 'Kalekim Kimyevi Maddeler Sanayi', sector: 'Yapı Kimyasalları & Yapıştırıcı', price: 28.50 },
  { symbol: 'KLMSN', name: 'Klimasan Klima Sanayi', sector: 'Ticari Soğutucu & Dondurucu', price: 21.00 },
  { symbol: 'KLNMA', name: 'Türkiye Kalkınma ve Yatırım Bankası', sector: 'Kalkınma Bankacılığı', price: 34.00 },
  { symbol: 'KLSER', name: 'Kaleseramik Çanakkale Kalebodur', sector: 'Seramik Kaplama & Vitrifiye', price: 44.50 },
  { symbol: 'KMPUR', name: 'Kimteks Poliüretan Sanayi', sector: 'Poliüretan Sistemleri', price: 38.00 },
  { symbol: 'KNFRT', name: 'Konfrut Gıda Sanayi', sector: 'Meyve ve Sebze İşleme', price: 12.80 },
  { symbol: 'KOCMT', name: 'Koç Metalurji A.Ş.', sector: 'Kütük Demir & İnşaat Demiri', price: 21.50 },
  { symbol: 'KONKA', name: 'Konya Kağıt Sanayi ve Ticaret', sector: 'Yazı Tabı Kağıdı & Defter', price: 48.00 },
  { symbol: 'KONTR', name: 'Kontrolmatik Teknoloji Enerji ve Mühendislik', sector: 'Enerji Depolama (Pomega) & Otomasyon', price: 46.80 },
  { symbol: 'KONYA', name: 'Konya Çimento Sanayii', sector: 'Çimento', price: 9800.00 },
  { symbol: 'KOPOL', name: 'Koza Polyester Sanayi', sector: 'Polyester Elyaf & Cips', price: 42.00 },
  { symbol: 'KORDS', name: 'Kordsa Teknik Tekstil A.Ş.', sector: 'Lastik Kord Bezi & Kompozit', price: 88.50 },
  { symbol: 'KOTON', name: 'Koton Mağazacılık Tekstil', sector: 'Hazır Giyim & Moda Perakendesi', price: 21.80 },
  { symbol: 'KOZAA', name: 'Koza Anadolu Metal Madencilik', sector: 'Metalik Maden Arama', price: 54.00 },
  { symbol: 'KOZAL', name: 'Koza Altın İşletmeleri A.Ş.', sector: 'Altın Madeni Üretimi', price: 23.90 },
  { symbol: 'KRDMD', name: 'Kardemir Karabük Demir Çelik (D)', sector: 'Ray, Ağır Profil & Çelik', price: 28.50 },
  { symbol: 'KRONT', name: 'Kron Telekomünikasyon Hizmetleri', sector: 'Ayrıcalıklı Erişim Yönetimi (PAM Yazılımı)', price: 24.50 },
  { symbol: 'KRVGD', name: 'Kervan Gıda Sanayi (Bebeto)', sector: 'Yumuşak Şekerleme (Jelly)', price: 2.35 },
  { symbol: 'KTSKR', name: 'Kütahya Şeker Fabrikası', sector: 'Şeker Üretimi', price: 58.00 },
  { symbol: 'KUTPO', name: 'Kütahya Porselen Sanayi', sector: 'Porselen Sofra Eşyası', price: 78.00 },

  // L - M
  { symbol: 'LIDER', name: 'Lider Filo Filo Kiralama', sector: 'Operasyonel Araç Kiralama', price: 54.00 },
  { symbol: 'LILAK', name: 'Lila Kağıt Sanayi (Sofia, Maylo)', sector: 'Temizlik Kağıtları İmalatı', price: 26.50 },
  { symbol: 'LINK', name: 'Link Bilgisayar Sistemleri', sector: 'Kurumsal ERP Yazılımları', price: 540.00 },
  { symbol: 'LMKDC', name: 'Limak Doğu Anadolu Çimento', sector: 'Çimento İmalatı', price: 28.50 },
  { symbol: 'LOGO', name: 'Logo Yazılım Sanayi ve Ticaret', sector: 'Kurumsal Yazılım & Fintek', price: 92.00 },
  { symbol: 'LUKSK', name: 'Lüks Kadife Ticaret ve Sanayii', sector: 'Kadife Kumaş İmalatı', price: 68.00 },
  { symbol: 'MACKO', name: 'Mackolik İnternet Hizmetleri', sector: 'Spor Medyası & Canlı Skor', price: 88.00 },
  { symbol: 'MAGEN', name: 'Margün Enerji Üretim', sector: 'Güneş Enerjisi Santralleri', price: 14.80 },
  { symbol: 'MAKIM', name: 'Makim Makina Teknolojileri', sector: 'Hassas Döküm & Geçiş Kontrol Turnikesi', price: 58.00 },
  { symbol: 'MAKTK', name: 'Makina Takım Endüstrisi', sector: 'Kesici Takımlar & Matkap Ucu', price: 8.50 },
  { symbol: 'MANAS', name: 'Manas Enerji Yönetimi Sanayi', sector: 'Akıllı Gaz & Su Sayaçları', price: 11.20 },
  { symbol: 'MARBL', name: 'Tureks Turunç Madencilik (Marble)', sector: 'Mermer & Traverten İhracatı', price: 16.50 },
  { symbol: 'MAVI', name: 'Mavi Giyim Sanayi ve Ticaret', sector: 'Denim & Moda Perakendeciliği', price: 98.00 },
  { symbol: 'MEKAG', name: 'Meka Beton Santralleri İmalat', sector: 'Beton Santrali & Kırma Eleme', price: 58.00 },
  { symbol: 'MGROS', name: 'Migros Ticaret A.Ş.', sector: 'Süpermarket & Online Alışveriş', price: 485.00 },
  { symbol: 'MIATK', name: 'Mia Teknoloji A.Ş.', sector: 'Yapay Zeka, Biyometri & Sağlık Bilişimi', price: 62.10 },
  { symbol: 'MOGAN', name: 'Mogan Enerji Yatırım Holding', sector: 'Rüzgar & Jeotermal Enerji', price: 13.80 },
  { symbol: 'MPARK', name: 'MLP Sağlık Hizmetleri (Medical Park & VM)', sector: 'Özel Hastane İşletmeciliği', price: 340.00 },
  { symbol: 'MTRKS', name: 'Matriks Bilgi Dağıtım Hizmetleri', sector: 'Finansal Piyasa Veri Terminali', price: 54.00 },

  // N - O - Ö
  { symbol: 'NATEN', name: 'Naturel Yenilenebilir Enerji Ticaret', sector: 'Güneş Enerjisi', price: 48.00 },
  { symbol: 'NETAS', name: 'Netaş Telekomünikasyon', sector: 'Haberleşme & 5G Altyapısı', price: 74.00 },
  { symbol: 'NTHOL', name: 'Net Holding A.Ş.', sector: 'Otel & Casino İşletmeciliği (Merit)', price: 38.00 },
  { symbol: 'NUGYO', name: 'Nurol Gayrimenkul Yatırım Ortaklığı', sector: 'GYO', price: 8.50 },
  { symbol: 'NUHCM', name: 'Nuh Çimento Sanayi A.Ş.', sector: 'Çimento & Liman', price: 310.00 },
  { symbol: 'OBAMS', name: 'Oba Makarnacılık Sanayi', sector: 'Makarna & İrmik Üretimi', price: 36.50 },
  { symbol: 'OBASE', name: 'Obase Bilgisayar ve Danışmanlık', sector: 'Perakende Analitiği Yazılımları', price: 48.00 },
  { symbol: 'ODAS', name: 'Odaş Elektrik Üretim Sanayi', sector: 'Kömür Santrali & Altın / Antimon', price: 7.80 },
  { symbol: 'OFSYM', name: 'Ofis Yem Gıda Sanayi', sector: 'Karma Hayvan Yemi', price: 44.00 },
  { symbol: 'ONCSM', name: 'Oncosem Onkolojik Sistemler', sector: 'Kemoterapi İlaç Hazırlama Sistemleri', price: 168.00 },
  { symbol: 'ORGE', name: 'Orge Enerji Elektrik Taahhüt', sector: 'Metro & Raylı Sistem Elektrik Taahhüt', price: 72.00 },
  { symbol: 'OTKAR', name: 'Otokar Otomotiv ve Savunma Sanayi', sector: 'Zırhlı Askeri Araç & Otobüs İmalatı', price: 480.00 },
  { symbol: 'OYAKC', name: 'Oyak Çimento Fabrikaları A.Ş.', sector: 'Çimento & Hazır Beton', price: 27.80 },
  { symbol: 'OZKGY', name: 'Özak Gayrimenkul Yatırım Ortaklığı', sector: 'GYO (Büyükyalı & Ela Resort)', price: 9.80 },
  { symbol: 'OZSUB', name: 'Özsu Balık Üretimi', sector: 'Kültür Balıkçılığı (Levrek & Çipura)', price: 24.50 },

  // P - R - S - Ş
  { symbol: 'PAPIL', name: 'Papilon Savunma Güvenlik Sistemleri', sector: 'Biyometrik Kimlik Doğrulama & Parmak İzi', price: 92.00 },
  { symbol: 'PARSN', name: 'Parsan Mahmuzlu Dövme Çelik', sector: 'Dövme Çelik Krank Mili & Aks', price: 88.00 },
  { symbol: 'PASEU', name: 'Pasifik Eurasia Lojistik', sector: 'Demiryolu Taşımacılığı', price: 68.00 },
  { symbol: 'PATEK', name: 'Pasifik Donanım ve Yazılım Bilgi', sector: 'Siber Güvenlik & Yazılım', price: 114.00 },
  { symbol: 'PETKM', name: 'Petkim Petrokimya Holding A.Ş.', sector: 'Etilen, Termoplastik & Kimya', price: 21.20 },
  { symbol: 'PETUN', name: 'Pınar Entegre Et ve Un Sanayii', sector: 'Et & Şarküteri Ürünleri', price: 88.00 },
  { symbol: 'PGSUS', name: 'Pegasus Hava Taşımacılığı A.Ş.', sector: 'Düşük Maliyetli Havayolu (LCC)', price: 234.00 },
  { symbol: 'PINSU', name: 'Pınar Su ve İçecek', sector: 'Ambalajlı Doğal Kaynak Suyu', price: 16.50 },
  { symbol: 'PNSUT', name: 'Pınar Süt Mamülleri Sanayii', sector: 'Süt, Peynir & Yoğurt', price: 94.00 },
  { symbol: 'POLHO', name: 'Polisan Holding A.Ş.', sector: 'Boya, Kimya & Liman', price: 13.80 },
  { symbol: 'POLTK', name: 'Politeknik Metal Sanayi', sector: 'Alüminyum Yüzey İşlem Kimyasalları', price: 8900.00 },
  { symbol: 'PRKAB', name: 'Türk Prysmian Kablo ve Sistemleri', sector: 'Enerji & Telekomünikasyon Kabloları', price: 34.00 },
  { symbol: 'QUAGR', name: 'Qua Granite Hayal Yapı Ürünleri', sector: 'Teknik Granit & Seramik', price: 3.80 },
  { symbol: 'RALYH', name: 'Ral Yatırım Holding', sector: 'İnşaat Taahhüt & Enerji', price: 198.00 },
  { symbol: 'REEDR', name: 'Reeder Teknoloji Sanayi ve Ticaret', sector: 'Akıllı Telefon, Tablet & Elektrikli Araç', price: 32.40 },
  { symbol: 'RNPOL', name: 'Rainbow Polikarbonat Sanayi', sector: 'Polikarbonat Levha', price: 28.00 },
  { symbol: 'RTALB', name: 'RTA Laboratuvarları Biyolojik Ürünler', sector: 'Tanı Kitleri & Moleküler Biyoloji', price: 12.80 },
  { symbol: 'RUBNS', name: 'Rubenis Tekstil Sanayi', sector: 'İplik, Kumaş & Güneş Enerjisi', price: 34.00 },
  { symbol: 'RYGYO', name: 'Reysaş Gayrimenkul Yatırım Ortaklığı', sector: 'Lojistik Depolama GYO', price: 42.00 },
  { symbol: 'RYSAS', name: 'Reysaş Taşımacılık ve Lojistik', sector: 'Entegre Lojistik & Depolama', price: 54.00 },
  { symbol: 'SAHOL', name: 'Hacı Ömer Sabancı Holding A.Ş.', sector: 'Holding (Bankacılık, Enerji, Sanayi, Dijital)', price: 98.40 },
  { symbol: 'SANEL', name: 'Sanel Mühendislik Elektrik', sector: 'Aydınlatma & Elektrik Taahhüt', price: 26.00 },
  { symbol: 'SASA', name: 'Sasa Polyester Sanayi A.Ş.', sector: 'Polyester Elyaf, İplik & PTA / DMT', price: 4.88 },
  { symbol: 'SAYAS', name: 'Say Yenilenebilir Enerji Ekipmanları', sector: 'Rüzgar Türbini Kule Ekipmanları', price: 68.00 },
  { symbol: 'SDTTR', name: 'SDT Uzay ve Savunma Teknolojileri', sector: 'Radar, Elektronik Harp & Simülasyon', price: 240.00 },
  { symbol: 'SELEC', name: 'Selçuk Ecza Deposu Ticaret', sector: 'İlaç Dağıtımı & Ecza Depoculuğu', price: 62.00 },
  { symbol: 'SISE', name: 'Türkiye Şişe ve Cam Fabrikaları (Şişecam)', sector: 'Düzcam, Cam Ambalaj, Cam Ev Eşyası & Soda Külü', price: 47.60 },
  { symbol: 'SKBNK', name: 'Şekerbank T.A.Ş.', sector: 'Bankacılık', price: 4.80 },
  { symbol: 'SMRTG', name: 'Smart Güneş Enerjisi Teknolojileri', sector: 'Fotovoltaik Güneş Paneli & EPC', price: 48.50 },
  { symbol: 'SNGYO', name: 'Sinpaş Gayrimenkul Yatırım Ortaklığı', sector: 'GYO', price: 4.20 },
  { symbol: 'SOKM', name: 'Şok Marketler Ticaret A.Ş.', sector: 'İndirim Market Zinciri', price: 54.00 },
  { symbol: 'SUWEN', name: 'Suwen Tekstil Sanayi', sector: 'İç Giyim & Ev Giyimi Perakendesi', price: 28.50 },

  // T
  { symbol: 'TABGD', name: 'TAB Gıda Sanayi ve Ticaret (Burger King, Popeyes)', sector: 'Hızlı Servis Restorancılığı', price: 145.00 },
  { symbol: 'TARKM', name: 'Tarkim Bitki Koruma Sanayi', sector: 'Tarımsal İlaç & Bitki Besleme', price: 590.00 },
  { symbol: 'TATEN', name: 'Tatlıpınar Enerji Üretim', sector: 'Rüzgar Enerjisi Santralleri', price: 34.00 },
  { symbol: 'TATGD', name: 'Tat Gıda Sanayi A.Ş. (Salça, Konserve)', sector: 'Salça & Domates Ürünleri', price: 28.00 },
  { symbol: 'TAVHL', name: 'TAV Havalimanları Holding', sector: 'Uluslararası Havalimanı İşletmeciliği', price: 265.00 },
  { symbol: 'TBORG', name: 'Türk Tuborg Bira ve Malt Sanayii', sector: 'Bira & İçecek', price: 104.00 },
  { symbol: 'TCELL', name: 'Turkcell İletişim Hizmetleri A.Ş.', sector: 'Mobil İletişim & Dijital Hizmetler', price: 94.00 },
  { symbol: 'TEZOL', name: 'Europap Tezol Kağıt Sanayi', sector: 'Temizlik Kağıtları İmalatı', price: 18.50 },
  { symbol: 'THYAO', name: 'Türk Hava Yolları A.O.', sector: 'Uluslararası Yolcu & Kargo Havayolu', price: 306.50 },
  { symbol: 'TKFEN', name: 'Tekfen Holding A.Ş.', sector: 'Taahhüt, Tarımsal Sanayi & Toros Gübre', price: 74.00 },
  { symbol: 'TKNSA', name: 'Teknosa İç ve Dış Ticaret', sector: 'Teknoloji Perakendeciliği', price: 34.50 },
  { symbol: 'TMSN', name: 'Tümosan Motor ve Traktör Sanayi', sector: 'Dizel Motor & Traktör İmalatı', price: 115.00 },
  { symbol: 'TNZTP', name: 'Tapdi Oksijen Özel Sağlık (Tınaztepe)', sector: 'Özel Hastane & Sağlık Hizmetleri', price: 8.50 },
  { symbol: 'TOASO', name: 'Tofaş Türk Otomobil Fabrikası A.Ş.', sector: 'Fiat, Egea & Otomotiv Üretimi', price: 235.00 },
  { symbol: 'TRILC', name: 'Türk İlaç ve Serum Sanayi', sector: 'Serum & Aşı Üretimi', price: 26.50 },
  { symbol: 'TSPOR', name: 'Trabzonspor Sportif Yatırım', sector: 'Spor Kulübü', price: 1.15 },
  { symbol: 'TTKOM', name: 'Türk Telekomünikasyon A.Ş.', sector: 'Sabit Hat, Fiber İnternet & Mobil', price: 49.20 },
  { symbol: 'TTRAK', name: 'Türk Traktör ve Ziraat Makineleri', sector: 'New Holland & Case IH Traktör', price: 780.00 },
  { symbol: 'TUKAS', name: 'Tukaş Gıda Sanayi ve Ticaret', sector: 'Salça, Turşu & Konserve', price: 6.80 },
  { symbol: 'TUPRS', name: 'Tüpraş Türkiye Petrol Rafinerileri A.Ş.', sector: 'Ham Petrol Rafinajı & Akaryakıt', price: 169.50 },
  { symbol: 'TURGG', name: 'Türker Proje Gayrimenkul Geliştirme', sector: 'Gayrimenkul Geliştirme', price: 740.00 },
  { symbol: 'TURSG', name: 'Türkiye Sigorta A.Ş.', sector: 'Elementer Sigortacılık (Lider)', price: 14.80 },

  // U - Ü - V - Y - Z
  { symbol: 'ULKER', name: 'Ülker Bisküvi Sanayi A.Ş.', sector: 'Bisküvi, Çikolata & Kek İmalatı', price: 148.00 },
  { symbol: 'UNLU', name: 'Ünlü Yatırım Holding', sector: 'Yatırım Bankacılığı & Portföy', price: 16.50 },
  { symbol: 'USAK', name: 'Uşak Seramik Sanayii', sector: 'Seramik & Porselen Karo', price: 14.20 },
  { symbol: 'VAKBN', name: 'Türkiye Vakıflar Bankası T.A.O.', sector: 'Bankacılık', price: 22.40 },
  { symbol: 'VAKKO', name: 'Vakko Tekstil ve Hazır Giyim', sector: 'Lüks Moda & Giyim Perakendesi', price: 92.00 },
  { symbol: 'VBTYZ', name: 'VBT Yazılım A.Ş.', sector: 'Kurumsal BT & Anaçatı Yazılımları', price: 34.00 },
  { symbol: 'VERUS', name: 'Verusa Holding A.Ş.', sector: 'Girişim Sermayesi & Madencilik', price: 310.00 },
  { symbol: 'VESBE', name: 'Vestel Beyaz Eşya Sanayi ve Ticaret', sector: 'Buzdolabı, Çamaşır Makinesi İhracatı', price: 21.40 },
  { symbol: 'VESTL', name: 'Vestel Elektronik Sanayi ve Ticaret', sector: 'TV, Ekran & Tüketici Elektroniği', price: 78.50 },
  { symbol: 'VRGYO', name: 'Vera Konsept Gayrimenkul Yatırım', sector: 'GYO', price: 38.00 },
  { symbol: 'YATAS', name: 'Yataş Yatak ve Yorgan Sanayi', sector: 'Yatak, Baza & Mobilya (Enza Home)', price: 32.50 },
  { symbol: 'YEOTK', name: 'Yeo Teknoloji Enerji ve Endüstri', sector: 'Elektrifikasyon & Otomasyon', price: 215.00 },
  { symbol: 'YKBNK', name: 'Yapı ve Kredi Bankası A.Ş.', sector: 'Bankacılık (Koç Grubu)', price: 29.80 },
  { symbol: 'YUNSA', name: 'Yünsa Yünlü Sanayi ve Ticaret', sector: 'Yünlü Dokuma Kumaş İhracatı', price: 74.00 },
  { symbol: 'YYLGD', name: 'Yayla Agro Gıda Sanayi', sector: 'Pirinç, Bakliyat & Hazır Yemek', price: 12.80 },
  { symbol: 'ZOREN', name: 'Zorlu Enerji Elektrik Üretim A.Ş.', sector: 'Jeotermal, Rüzgar & Doğalgaz Santralleri', price: 5.20 },
  { symbol: 'ZRGYO', name: 'Ziraat Gayrimenkul Yatırım Ortaklığı', sector: 'GYO (İstanbul Finans Merkezi Ziraat Kuleleri)', price: 6.40 }
];

// Helper: Normalize Turkish string for insensitive search
function normalizeTurkishText(str) {
  if (!str) return '';
  return str.toString().toLowerCase()
    .replace(/ğ/g, 'g')
    .replace(/ü/g, 'u')
    .replace(/ş/g, 's')
    .replace(/ı/g, 'i')
    .replace(/i̇/g, 'i')
    .replace(/ö/g, 'o')
    .replace(/ç/g, 'c')
    .replace(/[^a-z0-9]/g, '');
}

window.BIST_ALL_COMPANIES = BIST_ALL_COMPANIES;
window.normalizeTurkishText = normalizeTurkishText;
