/**
 * BIST_STOCK_DATABASE - Arama Otomatik Tamamlama İçin Sabit Hisse Listesi
 */
window.BIST_STOCK_DATABASE = [
  { symbol: 'THYAO', name: 'Türk Hava Yolları', sector: 'Havacılık' },
  { symbol: 'ASELS', name: 'Aselsan Askeri Elektronik', sector: 'Savunma Sanayii' },
  { symbol: 'TUPRS', name: 'Tüpraş Türkiye Petrol Rafinerileri', sector: 'Enerji & Petrol' },
  { symbol: 'EREGL', name: 'Ereğli Demir ve Çelik', sector: 'Demir Çelik & Metal' },
  { symbol: 'SASA', name: 'Sasa Polyester Sanayi', sector: 'Kimya & Tekstil' },
  { symbol: 'BIMAS', name: 'BİM Birleşik Mağazalar', sector: 'Perakende Ticaret' },
  { symbol: 'AKBNK', name: 'Akbank T.A.Ş.', sector: 'Bankacılık' },
  { symbol: 'GARAN', name: 'Türkiye Garanti Bankası', sector: 'Bankacılık' },
  { symbol: 'KCHOL', name: 'Koç Holding A.Ş.', sector: 'Holding & Yatırım' },
  { symbol: 'SAHOL', name: 'Sabancı Holding A.Ş.', sector: 'Holding & Yatırım' },
  { symbol: 'SISE', name: 'Türkiye Şişe ve Cam Fabrikaları', sector: 'Cam & Sanayi' },
  { symbol: 'FROTO', name: 'Ford Otomotiv Sanayi', sector: 'Otomotiv' },
  { symbol: 'TOASO', name: 'Tofaş Türk Otomobil Fabrikası', sector: 'Otomotiv' },
  { symbol: 'PETKM', name: 'Petkim Petrokimya Holding', sector: 'Petrokimya' },
  { symbol: 'YKBNK', name: 'Yapı ve Kredi Bankası', sector: 'Bankacılık' },
  { symbol: 'ISCTR', name: 'Türkiye İş Bankası (C)', sector: 'Bankacılık' },
  { symbol: 'HALKB', name: 'Türkiye Halk Bankası', sector: 'Bankacılık' },
  { symbol: 'VAKBN', name: 'Türkiye Vakıflar Bankası', sector: 'Bankacılık' },
  { symbol: 'PGSUS', name: 'Pegasus Hava Taşımacılığı', sector: 'Havacılık' },
  { symbol: 'ARCLK', name: 'Arçelik A.Ş.', sector: 'Dayanıklı Tüketim' },
  { symbol: 'ENKAI', name: 'Enka İnşaat ve Sanayi', sector: 'İnşaat & Taahhüt' },
  { symbol: 'KOZAL', name: 'Koza Altın İşletmeleri', sector: 'Madencilik & Altın' },
  { symbol: 'KOZAA', name: 'Koza Anadolu Metal Madencilik', sector: 'Madencilik' },
  { symbol: 'IPEKE', name: 'İpek Doğal Enerji', sector: 'Enerji' },
  { symbol: 'ALARK', name: 'Alarko Holding', sector: 'Holding & Enerji' },
  { symbol: 'ASTOR', name: 'Astor Enerji A.Ş.', sector: 'Enerji Ekipmanları' },
  { symbol: 'EUPWR', name: 'Europower Enerji ve Otomasyon', sector: 'Yenilenebilir Enerji' },
  { symbol: 'GESAN', name: 'Girişim Elektrik Sanayi', sector: 'Elektrik & Enerji' },
  { symbol: 'KONTR', name: 'Kontrolmatik Teknoloji Enerji', sector: 'Teknoloji & Enerji' },
  { symbol: 'MIATK', name: 'Mia Teknoloji A.Ş.', sector: 'Yazılım & Bilişim' },
  { symbol: 'REEDR', name: 'Reeder Teknoloji Sanayi', sector: 'Elektronik & Teknoloji' },
  { symbol: 'EKGYO', name: 'Emlak Konut GYO', sector: 'Gayrimenkul Yatırım' },
  { symbol: 'ISGYO', name: 'İş Gayrimenkul Yatırım Ortaklığı', sector: 'Gayrimenkul' },
  { symbol: 'HEKTS', name: 'Hektaş Ticaret T.A.Ş.', sector: 'Tarım İlaçları & Kimya' },
  { symbol: 'VESTL', name: 'Vestel Elektronik Sanayi', sector: 'Elektronik' },
  { symbol: 'VESBE', name: 'Vestel Beyaz Eşya Sanayi', sector: 'Beyaz Eşya' },
  { symbol: 'TTKOM', name: 'Türk Telekomünikasyon', sector: 'Telekomünikasyon' },
  { symbol: 'TCELL', name: 'Turkcell İletişim Hizmetleri', sector: 'Telekomünikasyon' },
  { symbol: 'MGROS', name: 'Migros Ticaret A.Ş.', sector: 'Perakende Market' },
  { symbol: 'SOKM', name: 'Şok Marketler Ticaret', sector: 'Perakende Market' },
  { symbol: 'ULKER', name: 'Ülker Bisküvi Sanayi', sector: 'Gıda & Şekerleme' },
  { symbol: 'AEFES', name: 'Anadolu Efes Biracılık', sector: 'İçecek' },
  { symbol: 'CCOLA', name: 'Coca-Cola İçecek', sector: 'İçecek' },
  { symbol: 'DOAS', name: 'Doğuş Otomotiv', sector: 'Otomotiv' },
  { symbol: 'GWIND', name: 'Galata Wind Enerji', sector: 'Enerji' },
  { symbol: 'TUKAS', name: 'Tukaş Gıda Sanayi', sector: 'Gıda' },
  { symbol: 'ZOREN', name: 'Zorlu Enerji', sector: 'Enerji' },
  { symbol: 'ODAS', name: 'Odaş Elektrik', sector: 'Enerji' }
];
